name = "Ainforge"
author = "Trojan-V"
version = "2.1.0"
description = "Ainforge provides pre-configured mods, aiming to provide a seemless experience while playing Cactus Clicker on the PlayLegend server network."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a218d25c370d782579b92a019bebec4920448b9790eb1f88cf69d7ffdfbd817"

[versions]
fabric = "0.18.4"
minecraft = "1.21.8"

[options]
acceptable-game-versions = ["1.21.8"]
